### ISSUE TITLE
JoinStykerJsonFile function is not working properly

### ISSUE THREAD

**Issue by sarthak4allworks** [rajbos/Stryker.MultipleProjectRunner#5]
JoinStykerJsonFile function is not merging the JSON correctly.
This may be because of some format change in a generated JSON file.

**Comment by sarthak4allworks** [comment]
below modification in the function worked for me:

`function JoinStykerJsonFile ($additionalFile, $joinedFileName) {
    # Stryker report json files object is not an array :-(, so we cannot join them and have to do it manually
    $report = (Get-Content $joinedFileName | Out-String)
    $additionalContent = (Get-Content $additionalFile | Out-String)
    $searchString = '"files":{'
    $searchStringLength = $searchString.Length
    $startCopy = $additionalContent.IndexOf($searchString)
    $offSet = 2
    $copyText = $additionalContent.Substring($startCopy+$searchStringLength, $additionalContent.Length-$offSet-$startCopy-$searchStringLength)
    # save the first part of the report file
	$lastIndex = $report.LastIndexOf('}}')
    $startCopy = $report.Substring(0, $lastIndex)
    # add in the new copy text
    $startCopy = $startCopy + ", " + $copyText
    # add in the end of the file again
    $fileEnding = $report.Substring($report.Length-$offSet, $offSet)
    $startCopy = $startCopy + $fileEnding
    # save the new file to disk
    Set-Content -Path $joinedFileName -Value $startCopy
}`

**Comment by rajbos** [comment]
Would you be so kind to send in a PR for this @sarthak4allworks ? I'll be happy to include it!

**Comment by sarthak4allworks** [comment]
@rajbos 
I am trying to push my changes but getting an error:
![image](https://user-images.githubusercontent.com/16571452/168456948-54defb05-20ef-46f3-8bf7-36e421e58539.png)

Any permission required from your end?

**Comment by rajbos** [comment]
Well, you don't have any rights to push it into my repo. 

The normal way of working in open source, is to create a fork and then propose the changes in a Pull Request. Some more I got here: https://www.howtogeek.com/devops/how-to-properly-fork-a-github-repository/

Since you already have a local repo, I'd suggest to:

1. Fork my repo into your own GitHub account
2. Configure your local repo with an extra remote that points to your new GitHub repo
3. Push to your new GitHub repo (branch doesn't matter, can be main)
4. Then propose a PR to my repo

That way I do not need to give you write access to my repo, which is safer for me (I don't really know you 😉) and you use the common way to do this on GitHub: by using a fork

**Comment by sarthak4allworks** [comment]
Thanks for the response, I was not aware of this since I am working on open source first time.
I have done the changes in the way you have suggested above.

**Comment by rajbos** [comment]
Awesome stuff @sarthak4allworks! Merging it right in!

![TNMT team slogan: cowabunga](https://media.giphy.com/media/VgeGEVTdwzZao/giphy.gif)

**Comment by sarthak4allworks** [comment]
@rajbos 
I think my changes are not yet merged.

**Comment by rajbos** [comment]
Whoops. You are completely right. I mixed up closing the issues and the Pull Request. I've merged it in now 👍
